### ISSUE TITLE
问一下dalao有加入更多筛选项的计划吗？

### ISSUE THREAD

**Issue by Neutron3529** [jiangsichengchn/NpcScan#3]
目前我实现了遍历坟墓获取物品，区分活人死人，区分男生女相以及性取向，外加区分人物归属城镇，村庄，门派或者太吾村
（顺便把自己的前后端通信Mod接进去了，这样NpcScan Mod不必引用0Harmony.dll）
同时把归属的filter从Equals改成了Contains
把bool的判断改成了位运算

因为改了不少地方（因为我是Linux，一切以命令行编译方便为准……），没办法保证提交一个具体的PR而不出兼容性问题
改好的代码暂时放在gitee上，https://gitee.com/Neutron3529/MiChangSheng_Mod/tree/master/Taiwu!/NpcScan
如果你短时间内不准备更新这个Mod，我会在几周之后把Mod送进创意工坊。

---

BTW, 改UI真是改得我内息断绝

---

Update:目前加入了快速祠堂灌顶功能，可以在打开祠堂灌顶界面之后用NPCScan对NPC进行灌顶。
之前忘记说了，我加入了战斗检测，战斗时NPCScan自动失效
或许你也可以试试？
不然在战斗时候不小心按一下F3切换武器……

**Comment by jiangsichengchn** [comment]
直接发布吧，没有时间关注这个MOD了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年4月2日 19:22
收件人: ***@***.***>
抄送: ***@***.***>
主题: [jiangsichengchn/NpcScan] 问一下dalao有加入更多筛选项的计划吗？ (Issue #3)


目前我实现了遍历坟墓获取物品，区分活人死人，区分男生女相以及性取向，外加区分人物归属城镇，村庄，门派或者太吾村
（顺便把自己的前后端通信Mod接进去了，这样NpcScan Mod不必引用0Harmony.dll）
同时把归属的filter从Equals改成了Contains
把bool的判断改成了位运算

因为改了不少地方（因为我是Linux，一切以命令行编译方便为准……），没办法保证提交一个具体的PR而不出兼容性问题
改好的代码暂时放在gitee上，https://gitee.com/Neutron3529/MiChangSheng_Mod/tree/master/Taiwu!/NpcScan
如果你短时间内不准备更新这个Mod，我会在几周之后把Mod送进创意工坊。


BTW, 改UI真是改得我内息断绝

―

**Comment by Neutron3529** [comment]
现在我优化的NpcScan已经基本稳定了
给你发了好友申请
如果你接受的话我就可以在我的优化版把你挂成共同作者了。

BTW，如果你未来还准备做NpcScan，可以参考一下我的序列化部分(gen.py)。
序列化我写了好久……而序列化的部分可以让NpcScan的响应速度快很多很多。

**Comment by jiangsichengchn** [comment]
你来独立开发即可，很早之前我就不再向NpcScan添加功能了
